---
title: "Análise da base RAIS"
description: |
  Esta análise teve como objetivo analisar os salários na base da RAIS.
  
author:
  - name: Alan Santos

date: "`r format(Sys.time(), '%d %b, %Y')`"
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Neste relatório estamos interessados em responder a pergunta:

"Quanto ganha um cientista de dados?"

Para isso, vamos utilizar a base da RAIS anonimazada

# Acessando os dados da RAIS

Vamos utilizar o [datalake da iniciativa base dos dados](https://basedosdados.org).

```{r message=FALSE, warning=FALSE}
library(bigrquery)
library(tidyverse)
```


Segue abaixo,  o código que carrega as primeiras 5 linhas da tabela de microdados

```{r}
# ler um arquivo
tab_normal <- read.csv("https://raw.githubusercontent.com/curso-r/main-r4ds-1/master/dados/imdb.csv")

head(tab_normal, n = 5)

```


```{r, cache=TRUE}
# usando SGDB (máquina - processa e envia os dados)
conexao <- dbConnect(
        bigquery(), 
        project = "basedosdados",
        dataset = "br_me_rais",
        billing = "semanadsp"
)

# conexao simples entre o r e a tabela do google(robo)

base <- collect(select(tbl(conexao, "microdados_vinculos"),
everything(), 5))


head(base)
```

